# Generated by Django 5.2.8 on 2026-07-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
